## YAML Template.
---
#spring:
#    datasource:
#        driverClassName: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/blogr
#        username: root
#        password: root
        